language: php
dist: trusty
sudo: required

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0

env:
  - ENGINE=PDO_MYSQL_MARIADB55
  - ENGINE=PDO_MYSQL_MARIADB10
  - ENGINE=PDO_PGSQL
  - ENGINE=SQLite3
  - ENGINE=GEOS34
  - ENGINE=GEOS35
  - ENGINE=GEOS36
  - ENGINE=GEOS37
  - ENGINE=GEOS38

matrix:
  include:
    # MySQL 5.6 is the default on Trusty
    - dist: trusty
      env: ENGINE=PDO_MYSQL56
      php: 7.1
    - dist: trusty
      env: ENGINE=PDO_MYSQL56
      php: 7.2
    - dist: trusty
      env: ENGINE=PDO_MYSQL56
      php: 7.3

    # MySQL 5.7 is the default on Xenial
    - dist: xenial
      env: ENGINE=PDO_MYSQL57
      php: 7.1
    - dist: xenial
      env: ENGINE=PDO_MYSQL57
      php: 7.2
    - dist: xenial
      env: ENGINE=PDO_MYSQL57
      php: 7.3
    - dist: xenial
      env: ENGINE=PDO_MYSQL57
      php: 7.4

    - dist: xenial
      env: ENGINE=PDO_MYSQL80
      php: 7.1
    - dist: xenial
      env: ENGINE=PDO_MYSQL80
      php: 7.2
    - dist: xenial
      env: ENGINE=PDO_MYSQL80
      php: 7.3

# @todo currently getting "Unexpected server response while doing caching_sha2 auth" on PHP 7.4
#    - dist: xenial
#      env: ENGINE=PDO_MYSQL80
#      php: 7.4

    - dist: xenial
      env: ENGINE=SQLite3
      php: 7.4

before_script:
  - if [[ $ENGINE = PDO_MYSQL56 ]]; then ENGINE=PDO_MYSQL; fi;
  - if [[ $ENGINE = PDO_MYSQL57 ]]; then ENGINE=PDO_MYSQL; sudo apt-get install mysql-server; sudo systemctl start mysql; fi;
  - if [[ $ENGINE = PDO_MYSQL80 ]]; then ENGINE=PDO_MYSQL; sudo bash travis/install-mysql-8.0.sh; fi;
  - if [[ $ENGINE = PDO_MYSQL_MARIADB55 ]]; then ENGINE=PDO_MYSQL; sudo VERSION=5.5 bash travis/install-mariadb.sh; fi;
  - if [[ $ENGINE = PDO_MYSQL_MARIADB10 ]]; then ENGINE=PDO_MYSQL; sudo VERSION=10.0 bash travis/install-mariadb.sh; fi;
  - if [[ $ENGINE = PDO_PGSQL ]]; then bash travis/install-postgis.sh; fi;
  - if [[ $ENGINE = GEOS34 ]]; then ENGINE=GEOS; VERSION=3.4.3 bash travis/install-geos.sh; fi;
  - if [[ $ENGINE = GEOS35 ]]; then ENGINE=GEOS; VERSION=3.5.2 bash travis/install-geos.sh; fi;
  - if [[ $ENGINE = GEOS36 ]]; then ENGINE=GEOS; VERSION=3.6.4 bash travis/install-geos.sh; fi;
  - if [[ $ENGINE = GEOS37 ]]; then ENGINE=GEOS; VERSION=3.7.3 bash travis/install-geos.sh; fi;
  - if [[ $ENGINE = GEOS38 ]]; then ENGINE=GEOS; VERSION=3.8.0 bash travis/install-geos.sh; fi;
  - if [[ $ENGINE = SQLite3 ]]; then bash travis/install-spatialite.sh; fi;
  - composer install

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - vendor/bin/php-coveralls -v
